[general]
fontname=DejaVu Sans Mono 10
selcolor=#000000
bgcolor=#000000
fgcolor=#ffffff
disablerethink=1
hide_menubar=1
hide_toolbar=1
hide_statusbar=1
scrollback=1000
cursor_blink=1
visual_bell=0
audible_bell=0
